[project]
name = "jp-audiobook-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hermanismail", email = "hermanismail@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=6.0.0",
    "pillow>=12.3.0",
]

[project.scripts]
jp-audiobook-generator = "jp_audiobook_generator:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
